version: '3.3'
volumes:
  db-mysql:
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - .docker/app/.env
    environment:
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: django_study
      DATABASE_USER: admin
      DATABASE_PASSWORD: 2wsxdr%tgbhu8
      SECRET_KEY: 7j1=$$p)@db9hsihu3plz5drzkkb2pfw0kz&o*bqn#4o0s!bh#c
      DJANGO_DEBUG: 'Trueg'
      ALLOWED_HOSTS: '*'
    command: >
      dockerize -wait tcp://db:3306 -timeout 5m -wait-retry-interval 5s bash -c "
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: "no"
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      -  db-mysql:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: django_study
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2wsxdr%tgbhu8
    ports:
      - 3306:3306
    restart: "no"
