version: '3.3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
