version: '3.3'
volumes:
  db-mysql:
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      -  db-mysql:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: django_study
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2wsxdr%tgbhu8
    ports:
      - 3306:3306
    restart: "no"
