# Generated by Django 3.0 on 2019-12-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
